### PR TITLE
fix: network conversions

### LINKED ISSUE #248: Ensure correct impl From `blockchain::Network` for external network
:warning: Network `Local` should resolve into Monero `Mainnet`. Monero regtest uses the same magic bytes as mainnet.

### PR DESCRIPTION
**Pull request by h4sh3d**
Fix #248

When reviewing #247 I missed the conversion flow, it should be `blockchain::Network` -> `btc|xmr::Network` and not the inverse. And the issue was not describing the problem correctly, sorry for that.

### CODE REVIEW

File: src/blockchain.rs [hunk 1]
```diff
@@ -428,29 +428,42 @@ impl FromStr for Network {
     }
 }
 
-impl From<bitcoin::Network> for Network {
```
Comment (TheCharlatan) [inline src/blockchain.rs:431]: Can we get both directions?

Comment (h4sh3d) [reply src/blockchain.rs:431]: Yes we actually can. I rework the commits to not erase the work from @LeoNero as much as I can, thus I have to move the impl from the  `blockchain` module into `bitcoin`. If this bothers you @LeoNero I can remove that part and you do another PR yourself. I should have catch that in your first PR but I didn't, sorry for that.

Comment (TheCharlatan) [reply src/blockchain.rs:431]: Let's merge this to keep the momentum going. Leo's work is accurately preserved here and if there is something bothering him with the PR here, he can always submit a fresh PR to add more docs/test/functionality.

Comment (LeoNero) [reply src/blockchain.rs:431]: Hi just saw that. There is no problem removing my implementation for things to work properly or for better code organization.
